# Generated by Django 3.1.7 on 2021-11-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('cost', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChefProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('cost', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('profession', models.CharField(choices=[('Avocat', 'Avocat'), ('Expert-comptable', 'Expert-comptable'), ('Maire', 'Maire')], max_length=200, null=True)),
                ('statut', models.CharField(choices=[('Client', 'Client'), ('Lead qualifié', 'Lead qualifié'), ('Prospect', 'Prospect')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngenieurSon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('cost', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('cost', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=200, null=True)),
                ('stage', models.CharField(choices=[('En pré-production', 'En pré-production'), ('En production', 'En production'), ('En post-production', 'En post-production'), ('Publiée', 'Publiée')], max_length=200, null=True)),
                ('datePublication', models.DateField(null=True)),
                ('lieuTournage', models.CharField(choices=[('Studio 1', 'Studio 1'), ('Studio 2', 'Studio 2'), ('Studio 3', 'Studio 3')], max_length=200, null=True)),
                ('dateTournage', models.DateField(null=True)),
                ('heureTournage', models.TimeField(null=True)),
                ('revenusGen', models.FloatField(null=True)),
                ('impressionsLinkedin', models.FloatField(null=True)),
                ('likesLinkedin', models.FloatField(null=True)),
                ('partagesLinkedin', models.FloatField(null=True)),
                ('impressionsFacebook', models.FloatField(null=True)),
                ('likesFacebook', models.FloatField(null=True)),
                ('partagesFacebook', models.FloatField(null=True)),
                ('impressionsInstagram', models.FloatField(null=True)),
                ('likesInstagram', models.FloatField(null=True)),
                ('partagesInstagram', models.FloatField(null=True)),
                ('impressionsTwitter', models.FloatField(null=True)),
                ('likesTwitter', models.FloatField(null=True)),
                ('partagesTwitter', models.FloatField(null=True)),
                ('cadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cadreur')),
                ('chefProjet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.chefprojet')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.client')),
                ('ingénieurSon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ingenieurson')),
                ('monteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.monteur')),
            ],
        ),
    ]
